### ISSUE TITLE
App installation fails with "no module yaml"

### ISSUE THREAD

**Issue by czen** [YunoHost-Apps/jupyterlab_ynh#10]
I recently had to reinstall Jupyterlab on my Yunohost instance, but now it fails to install with this error:

```
!!

jupyterlab's script has encountered an error. Its execution was cancelled.

!!

ModuleNotFoundError: No module named 'yaml'

File "", line 1, in

Traceback (most recent call last):

ModuleNotFoundError: No module named 'yaml'

File "", line 1, in

Traceback (most recent call last):

Configuring Jupyter Notebook...

[LabBuildApp] > node /opt/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build

[LabBuildApp] > node /opt/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
```

Related part of the full log:

```
2019-04-22 21:13:38,223: INFO - Configuring Jupyter Notebook...
2019-04-22 21:13:38,224: DEBUG - ++ ynh_app_setting_get --app=jupyterlab --key=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,224: DEBUG - ++ local legacy_args=ak
2019-04-22 21:13:38,224: DEBUG - ++ args_array=([a]=app= [k]=key=)
2019-04-22 21:13:38,224: DEBUG - ++ declare -Ar args_array
2019-04-22 21:13:38,224: DEBUG - ++ local app
2019-04-22 21:13:38,225: DEBUG - ++ local key
2019-04-22 21:13:38,225: DEBUG - ++ ynh_handle_getopts_args --app=jupyterlab --key=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,225: DEBUG - ++ set +x
2019-04-22 21:13:38,225: DEBUG - ++ ynh_app_setting get jupyterlab checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,225: DEBUG - ++ ACTION=get
2019-04-22 21:13:38,225: DEBUG - ++ APP=jupyterlab
2019-04-22 21:13:38,225: DEBUG - ++ KEY=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,226: DEBUG - ++ VALUE=
2019-04-22 21:13:38,226: DEBUG - ++ python -
2019-04-22 21:13:38,326: DEBUG - + local checksum_value=
2019-04-22 21:13:38,327: WARNING - Traceback (most recent call last):
2019-04-22 21:13:38,328: DEBUG - + backup_file_checksum=
2019-04-22 21:13:38,328: WARNING -   File "<stdin>", line 1, in <module>
2019-04-22 21:13:38,328: DEBUG - + '[' -n '' ']'
2019-04-22 21:13:38,328: WARNING - ModuleNotFoundError: No module named 'yaml'
2019-04-22 21:13:38,329: DEBUG - + cp -f ../conf/jupyter_notebook_config.py /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,329: DEBUG - + ynh_replace_string __ENABLE_TERMINAL__ 1 /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,329: DEBUG - + local legacy_args=mrf
2019-04-22 21:13:38,329: DEBUG - + args_array=([m]=match_string= [r]=replace_string= [f]=target_file=)
2019-04-22 21:13:38,329: DEBUG - + declare -Ar args_array
2019-04-22 21:13:38,329: DEBUG - + local match_string
2019-04-22 21:13:38,330: DEBUG - + local replace_string
2019-04-22 21:13:38,330: DEBUG - + local target_file
2019-04-22 21:13:38,330: DEBUG - + ynh_handle_getopts_args __ENABLE_TERMINAL__ 1 /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,330: DEBUG - + set +x
2019-04-22 21:13:38,331: DEBUG - + echo '! Helper used in legacy mode !'
2019-04-22 21:13:38,331: DEBUG - + set +x
2019-04-22 21:13:38,331: DEBUG - + local delimit=@
2019-04-22 21:13:38,331: DEBUG - + match_string=__ENABLE_TERMINAL__
2019-04-22 21:13:38,331: DEBUG - + replace_string=1
2019-04-22 21:13:38,331: DEBUG - + sudo sed --in-place s@__ENABLE_TERMINAL__@1@g /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,432: DEBUG - + ynh_store_file_checksum /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,432: DEBUG - + local legacy_args=f
2019-04-22 21:13:38,432: DEBUG - + args_array=([f]=file=)
2019-04-22 21:13:38,432: DEBUG - + declare -Ar args_array
2019-04-22 21:13:38,433: DEBUG - + local file
2019-04-22 21:13:38,433: DEBUG - + ynh_handle_getopts_args /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,433: DEBUG - + set +x
2019-04-22 21:13:38,433: DEBUG - + echo '! Helper used in legacy mode !'
2019-04-22 21:13:38,433: DEBUG - + set +x
2019-04-22 21:13:38,433: DEBUG - + local checksum_setting_name=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,434: DEBUG - ++ cut '-d ' -f1
2019-04-22 21:13:38,434: DEBUG - ++ sudo md5sum /opt/jupyterlab/etc/jupyter/jupyter_notebook_config.py
2019-04-22 21:13:38,434: DEBUG - + ynh_app_setting_set --app=jupyterlab --key=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py --value=638511314106ed571eb04a190e9c1c61
2019-04-22 21:13:38,434: DEBUG - + local legacy_args=akv
2019-04-22 21:13:38,434: DEBUG - + args_array=([a]=app= [k]=key= [v]=value=)
2019-04-22 21:13:38,434: DEBUG - + declare -Ar args_array
2019-04-22 21:13:38,434: DEBUG - + local app
2019-04-22 21:13:38,434: DEBUG - + local key
2019-04-22 21:13:38,435: DEBUG - + local value
2019-04-22 21:13:38,435: DEBUG - + ynh_handle_getopts_args --app=jupyterlab --key=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py --value=638511314106ed571eb04a190e9c1c61
2019-04-22 21:13:38,435: DEBUG - + set +x
2019-04-22 21:13:38,435: DEBUG - + ynh_app_setting set jupyterlab checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py 638511314106ed571eb04a190e9c1c61
2019-04-22 21:13:38,437: DEBUG - + ACTION=set
2019-04-22 21:13:38,437: DEBUG - + APP=jupyterlab
2019-04-22 21:13:38,437: DEBUG - + KEY=checksum__opt_jupyterlab_etc_jupyter_jupyter_notebook_config.py
2019-04-22 21:13:38,438: DEBUG - + VALUE=638511314106ed571eb04a190e9c1c61
2019-04-22 21:13:38,438: DEBUG - + python -
2019-04-22 21:13:38,538: DEBUG - + ynh_exit_properly
2019-04-22 21:13:38,539: WARNING - Traceback (most recent call last):
2019-04-22 21:13:38,539: DEBUG - + local exit_code=1
2019-04-22 21:13:38,539: WARNING -   File "<stdin>", line 1, in <module>
2019-04-22 21:13:38,540: DEBUG - + '[' 1 -eq 0 ']'
2019-04-22 21:13:38,540: WARNING - ModuleNotFoundError: No module named 'yaml'
2019-04-22 21:13:38,540: DEBUG - + trap '' EXIT
2019-04-22 21:13:38,541: WARNING - !!
2019-04-22 21:13:38,541: DEBUG - + set +eu
2019-04-22 21:13:38,541: WARNING -   jupyterlab's script has encountered an error. Its execution was cancelled.
2019-04-22 21:13:38,542: DEBUG - + echo -e '!!\n  jupyterlab'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-04-22 21:13:38,542: WARNING - !!
2019-04-22 21:13:38,542: DEBUG - + type -t ynh_clean_setup
2019-04-22 21:13:38,542: WARNING - 
2019-04-22 21:13:38,543: DEBUG - + ynh_die
2019-04-22 21:13:38,543: DEBUG - + local legacy_args=mc
2019-04-22 21:13:38,543: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-04-22 21:13:38,543: DEBUG - + declare -Ar args_array
2019-04-22 21:13:38,543: DEBUG - + local message
2019-04-22 21:13:38,543: DEBUG - + local ret_code
2019-04-22 21:13:38,544: DEBUG - + ynh_handle_getopts_args
2019-04-22 21:13:38,544: DEBUG - + set +x
2019-04-22 21:13:38,544: DEBUG - + echo ''
2019-04-22 21:13:38,544: DEBUG - + exit 1
```

What can I do to try and fix this?

Full installation log: 
http://pasted.co/478bc367

**Comment by kay0u** [comment]
Hi, thank you for your report, it should be fixed now, you can reinstall it :-)

**Comment by czen** [comment]
Thx, it works!
