### ISSUE TITLE
Spawn failed: Server at xxxx didn't respond in 30 seconds

### ISSUE THREAD

**Issue by dystopy** [YunoHost-Apps/jupyterlab_ynh#109]
Bonjour,

Première installation de Jupyter Lab sur mon instance Yunohost à jour (sur RPi3), je n'arrive pas à "spawner" un serveur, est ce que la log vous parle ?

Merci ! 

May 17 13:54:49 jupyterhub[30486]: [E 2022-05-17 13:54:49.025 JupyterHub log:189] 500 GET /jupyterlab/hub/spawn-pending/dystopy (dystopy@195.135.74.27) 104.88ms
May 17 13:54:51 jupyterhub[30486]: [I 2022-05-17 13:54:51.321 JupyterHub roles:482] Adding role server to token: <APIToken('a42a...', user='dystopy', client_id='jupyterhub')>
May 17 13:54:51 jupyterhub[30486]: [I 2022-05-17 13:54:51.357 JupyterHub provider:607] Creating oauth client jupyterhub-user-dystopy
May 17 13:54:51 jupyterhub[30486]: [I 2022-05-17 13:54:51.453 JupyterHub spawner:1563] Spawning jupyterhub-singleuser --config=/opt/jupyterlab/config/jupyter_notebook_config.py
May 17 13:54:52 jupyterhub[30486]: [I 2022-05-17 13:54:52.290 JupyterHub log:189] 302 GET /jupyterlab/hub/spawn/dystopy -> /jupyterlab/hub/spawn-pending/dystopy (dystopy@195.135.74.27) 1036.67ms
May 17 13:54:52 jupyterhub[30486]: [I 2022-05-17 13:54:52.370 JupyterHub pages:401] dystopy is pending spawn
May 17 13:54:52 jupyterhub[30486]: [I 2022-05-17 13:54:52.377 JupyterHub log:189] 200 GET /jupyterlab/hub/spawn-pending/dystopy (dystopy@195.135.74.27) 21.90ms
May 17 13:54:55 jupyterhub[30486]: Traceback (most recent call last):
May 17 13:54:55 jupyterhub[30486]:   File "/opt/jupyterlab/.venv/bin/jupyterhub-singleuser", line 5, in <module>
May 17 13:54:55 jupyterhub[30486]:     from jupyterhub.singleuser import main
May 17 13:54:55 jupyterhub[30486]:   File "/opt/jupyterlab/.venv/lib/python3.9/site-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
May 17 13:54:55 jupyterhub[30486]:     from .app import main
May 17 13:54:55 jupyterhub[30486]:   File "/opt/jupyterlab/.venv/lib/python3.9/site-packages/jupyterhub/singleuser/app.py", line 38, in <module>
May 17 13:54:55 jupyterhub[30486]:     raise _import_error
May 17 13:54:55 jupyterhub[30486]: TypeError: exceptions must derive from BaseException
May 17 13:55:01 jupyterhub[30486]: ERROR:asyncio:Task exception was never retrieved
May 17 13:55:01 jupyterhub[30486]: future: <Task finished name='Task-3022' coro=<BaseHandler.spawn_single_user() done, defined at /opt/jupyterlab/.venv/lib/python3.9/site-packages/jupyterhub/handlers/base.py:850> exception=HTTPError()>
May 17 13:55:01 jupyterhub[30486]: Traceback (most recent call last):
May 17 13:55:01 jupyterhub[30486]:   File "/opt/jupyterlab/.venv/lib/python3.9/site-packages/jupyterhub/handlers/base.py", line 1051, in spawn_single_user
May 17 13:55:01 jupyterhub[30486]:     await gen.with_timeout(
May 17 13:55:01 jupyterhub[30486]: tornado.util.TimeoutError: Timeout
May 17 13:55:01 jupyterhub[30486]: During handling of the above exception, another exception occurred:
May 17 13:55:01 jupyterhub[30486]: Traceback (most recent call last):
May 17 13:55:01 jupyterhub[30486]:   File "/opt/jupyterlab/.venv/lib/python3.9/site-packages/jupyterhub/handlers/base.py", line 1085, in spawn_single_user
May 17 13:55:01 jupyterhub[30486]:     raise web.HTTPError(
May 17 13:55:01 jupyterhub[30486]: tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for dystopy may contain details.)

**Comment by dystopy** [comment]
Je m'auto réponds, si ça peut aider quelqu'un !

Alors il s'agissait d'une erreur liée à la librairie ZMQ sous python 3.9 (problème de GLIB assez récurent sous le triptyque Raspberry Pi 3 / Python 3.9 / Debian Buster)


Solution de contournement : 

1 - Accéder à l'environnement virtuel de Jupyter :  source /opt/jupyterlab/.venv/bin/activate
2 - Désinstaller la lib :  pip uninstall pyzmq
3 - La réinstaller via les sources : pip install --no-binary=:all: pyzmq

Et c'est tout bon ! (Du moins chez moi)
