### ISSUE TITLE
SystemExit: Found database schema version 

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/jupyterlab_ynh#13]
```
Jun  6 13:51:39 y jupyterhub[28961]: [I 2019-06-06 13:51:39.936 JupyterHub app:2120] Using Authenticator: ldapauthenticator.ldapauthenticator.LDAPAuthenticator-1.2.2
Jun  6 13:51:39 y jupyterhub[28961]: [I 2019-06-06 13:51:39.936 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
Jun  6 13:51:39 y jupyterhub[28961]: [I 2019-06-06 13:51:39.938 JupyterHub app:1257] Loading cookie_secret from /opt/jupyterlab/jupyterhub_cookie_secret
Jun  6 13:51:39 y jupyterhub[28961]: Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
Jun  6 13:51:39 y jupyterhub[28961]: ERROR:asyncio:Task exception was never retrieved
Jun  6 13:51:39 y jupyterhub[28961]: future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(DatabaseSchemaMismatch('Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.'))>
Jun  6 13:51:39 y jupyterhub[28961]: Traceback (most recent call last):
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py", line 2492, in launch_instance
Jun  6 13:51:39 y jupyterhub[28961]:     loop.start()
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
Jun  6 13:51:39 y jupyterhub[28961]:     self.asyncio_loop.run_forever()
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
Jun  6 13:51:39 y jupyterhub[28961]:     self._run_once()
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
Jun  6 13:51:39 y jupyterhub[28961]:     handle._run()
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/asyncio/events.py", line 88, in _run
Jun  6 13:51:39 y jupyterhub[28961]:     self._context.run(self._callback, *self._args)
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
Jun  6 13:51:39 y jupyterhub[28961]:     await self.initialize(argv)
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py", line 2129, in initialize
Jun  6 13:51:39 y jupyterhub[28961]:     self.init_db()
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py", line 1449, in init_db
Jun  6 13:51:39 y jupyterhub[28961]:     self.exit(e)
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/traitlets/config/application.py", line 648, in exit
Jun  6 13:51:39 y jupyterhub[28961]:     sys.exit(exit_status)
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/app.py", line 1430, in init_db
Jun  6 13:51:39 y jupyterhub[28961]:     self.db_url, reset=self.reset_db, echo=self.debug_db, **self.db_kwargs
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/orm.py", line 814, in new_session_factory
Jun  6 13:51:39 y jupyterhub[28961]:     check_db_revision(engine)
Jun  6 13:51:39 y jupyterhub[28961]:   File "/opt/jupyterlab/lib/python3.7/site-packages/jupyterhub/orm.py", line 756, in check_db_revision
Jun  6 13:51:39 y jupyterhub[28961]:     found=alembic_revision, head=head
Jun  6 13:51:40 y jupyterhub[28961]: SystemExit: Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
Jun  6 13:51:40 y systemd[1]: jupyterlab.service: Main process exited, code=exited, status=1/FAILURE
Jun  6 13:51:40 y systemd[1]: jupyterlab.service: Unit entered failed state.
```

**Comment by arthurlogilab** [comment]
I've tried running (as root or as debian) : 

```
 PATH=/opt/jupyterlab/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/jupyterlab/bin/jupyterhub -f /etc/jupyterlab/jupyterhub_config.py upgrade-db
```

Which doesn't solve the problem.

**Comment by kay0u** [comment]
Hi, and thank you for your report.

The old version was an alpha of jupyterlab, Now I upgraded the package to 1.0.4.

Can you try to reinstall it please?

**Comment by arthurlogilab** [comment]
Upgrade is not working https://paste.yunohost.org/raw/upapiguleb Trying out an uninstall & install.

**Comment by arthurlogilab** [comment]
The error in the log seems gone. Thanks !
