### ISSUE TITLE
Failing to open "Terminal" 

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/jupyterlab_ynh#16]
```
Aug 20 14:55:57 y pipenv[8043]: [I 2019-08-20 14:55:57.780 SingleUserNotebookApp log:174] 101 GET /jupyterlab/user/arthur/terminals/websocket/1?token=[secret] (arthur@172.20.5.2) 3.53ms
Aug 20 14:55:57 y pipenv[8043]: TermSocket.open: 1
Aug 20 14:55:57 y pipenv[8043]: [I 2019-08-20 14:55:57.782 SingleUserNotebookApp management:302] New terminal with specified name: 1
Aug 20 14:55:57 y pipenv[8043]: TermSocket.open: Opened 1
Aug 20 14:55:57 y pipenv[8043]: [I 2019-08-20 14:55:57.793 SingleUserNotebookApp management:185] EOF on FD 67; stopping reading
Aug 20 14:55:57 y pipenv[8043]: [I 2019-08-20 14:55:57.895 SingleUserNotebookApp management:338] Terminal 1 closed
Aug 20 14:55:57 y pipenv[8043]: [E 2019-08-20 14:55:57.973 SingleUserNotebookApp web:1788] Uncaught exception GET /jupyterlab/user/arthur/terminals/websocket/1?token=e1da6c71c8844f08b8289dadb3fc28fb (172.20.5.2)
Aug 20 14:55:57 y pipenv[8043]:     HTTPServerRequest(protocol='http', host='y.intra.logilab.fr', method='GET', uri='/jupyterlab/user/arthur/terminals/websocket/1?token=e1da6c71c8844f08b8289dadb3fc28fb', version='HTTP/1.1', remote_ip='172.20.5.2')
Aug 20 14:55:57 y pipenv[8043]:     Traceback (most recent call last):
Aug 20 14:55:57 y pipenv[8043]:       File "/opt/jupyterlab/.venv/lib/python3.5/site-packages/tornado/websocket.py", line 649, in _run_callback
Aug 20 14:55:57 y pipenv[8043]:         result = callback(*args, **kwargs)
Aug 20 14:55:57 y pipenv[8043]:       File "/opt/jupyterlab/.venv/lib/python3.5/site-packages/notebook/terminal/handlers.py", line 37, in on_message
Aug 20 14:55:57 y pipenv[8043]:         super(TermSocket, self).on_message(message)
Aug 20 14:55:57 y pipenv[8043]:       File "/opt/jupyterlab/.venv/lib/python3.5/site-packages/terminado/websocket.py", line 84, in on_message
Aug 20 14:55:57 y pipenv[8043]:         self.terminal.resize_to_smallest()
Aug 20 14:55:57 y pipenv[8043]:     AttributeError: 'NoneType' object has no attribute 'resize_to_smallest'
Aug 20 14:55:57 y pipenv[8043]: Websocket closed
Aug 20 14:55:57 y pipenv[8043]: 14:55:57.976 [ConfigProxy] #033[31merror#033[39m: 503 GET /jupyterlab/user/arthur/terminals/websocket/1?token=e1da6c71c8844f08b8289dadb3fc28fb read ECONNRESET
```

In the interface, comes back to the "New document" window.

**Comment by kay0u** [comment]
Hi, I can reproduce this issue, but after a few hours I couldn't find any solution for now.

**Comment by kay0u** [comment]
Hi, I found the problem, can you try to update jupyterlab to check if it's fixed please?

**Comment by arthurlogilab** [comment]
It works ! Thanks a lot!

**Comment by kay0u** [comment]
You're welcome! Thank you for the feedback!
