### ISSUE TITLE
failed to start in yunohost 4

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/jupyterlab_ynh#63]
```
-- Logs begin at Tue 2020-09-08 07:01:14 UTC, end at Tue 2020-09-08 09:22:59 UTC. --
Sep 08 09:21:53 pipenv[420]: [C 2020-09-08 09:21:53.924 JupyterHub app:2517] Failed to start proxy
Sep 08 09:21:53 pipenv[420]:     Traceback (most recent call last):
Sep 08 09:21:53 pipenv[420]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/app.py", line 2515, in start
Sep 08 09:21:53 pipenv[420]:         await self.proxy.start()
Sep 08 09:21:53 pipenv[420]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/proxy.py", line 651, in start
Sep 08 09:21:53 pipenv[420]:         cmd, env=env, start_new_session=True, shell=shell
Sep 08 09:21:53 pipenv[420]:       File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
Sep 08 09:21:53 pipenv[420]:         restore_signals, start_new_session)
Sep 08 09:21:53 pipenv[420]:       File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
Sep 08 09:21:53 pipenv[420]:         raise child_exception_type(errno_num, err_msg, err_filename)
Sep 08 09:21:53 pipenv[420]:     FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'
Sep 08 09:21:53 pipenv[420]:     
Sep 08 09:21:53 pipenv[420]: 10
Sep 08 09:21:55 systemd[1]: jupyterlab.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
```

```
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.335 JupyterHub app:2240] Running JupyterHub version 1.1.0
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.338 JupyterHub app:2271] Using Authenticator: ldapauthenticator.ldapauthenticator.LDAPAuthenticator-1.3.2
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.340 JupyterHub app:2271] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.1.0
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.341 JupyterHub app:2271] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.1.0
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.365 JupyterHub app:1349] Loading cookie_secret from /opt/jupyterlab/jupyterhub_cookie_secret
Sep 08 09:22:46 pipenv[518]: [I 2020-09-08 09:22:46.653 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
Sep 08 09:22:47 pipenv[518]: [I 2020-09-08 09:22:47.202 JupyterHub app:1655] Not using whitelist. Any authenticated user will be allowed.
Sep 08 09:22:47 pipenv[518]: [I 2020-09-08 09:22:47.473 JupyterHub app:2311] Initialized 0 spawners in 0.039 seconds
Sep 08 09:22:47 pipenv[518]: [W 2020-09-08 09:22:47.505 JupyterHub proxy:643] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
Sep 08 09:22:47 pipenv[518]: [I 2020-09-08 09:22:47.506 JupyterHub proxy:646] Starting proxy @ http://:8082/jupyterlab
Sep 08 09:22:47 pipenv[518]: [E 2020-09-08 09:22:47.692 JupyterHub proxy:659] Failed to find proxy ['configurable-http-proxy']
Sep 08 09:22:47 pipenv[518]:     The proxy can be installed with `npm install -g configurable-http-proxy`.To install `npm`, install nodejs which includes `npm`.If you see an `EACCES` error or permissions error, refer to the `npm` documentation on How To Prevent Permissions Errors.
Sep 08 09:22:47 pipenv[518]: [C 2020-09-08 09:22:47.709 JupyterHub app:2517] Failed to start proxy
Sep 08 09:22:47 pipenv[518]:     Traceback (most recent call last):
Sep 08 09:22:47 pipenv[518]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/app.py", line 2515, in start
Sep 08 09:22:47 pipenv[518]:         await self.proxy.start()
Sep 08 09:22:47 pipenv[518]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/proxy.py", line 651, in start
Sep 08 09:22:47 pipenv[518]:         cmd, env=env, start_new_session=True, shell=shell
Sep 08 09:22:47 pipenv[518]:       File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
Sep 08 09:22:47 pipenv[518]:         restore_signals, start_new_session)
Sep 08 09:22:47 pipenv[518]:       File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
Sep 08 09:22:47 pipenv[518]:         raise child_exception_type(errno_num, err_msg, err_filename)
Sep 08 09:22:47 pipenv[518]:     FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'
Sep 08 09:22:47 pipenv[518]:     
Sep 08 09:22:47 pipenv[518]: 10
Sep 08 09:22:49 systemd[1]: jupyterlab.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by kay0u** [comment]
Does the folder `/opt/node_n/lib/node_modules/configurable-http-proxy/` exist?

**Comment by boistordu** [comment]
Yes it does exist seems very full with 
100dir and 1629 files according to true

**Comment by palouf34** [comment]
I have similitary problem.


see  the log


`  Started JupyterLab.`
 `  - Jan 18 14:33:55 pipenv[9943]: [I 2021-01-18 14:33:55.993 JupyterHub app:2349] Running JupyterHub version 1.3.0`
 `  - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:55.993 JupyterHub app:2380] Using Authenticator: l ldapauthenticator.ldapauthenticator.LDAPAuthenticator-1.3.2`
 `  - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:55.993 JupyterHub app:2380] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.3.0`
`  - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:55.993 JupyterHub app:2380] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.3.0`
`  - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:55.996 JupyterHub app:1420] Loading cookie_secret from /opt/jupyterlab/jupyterhub_cookie_secret`
 ` - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:56.059 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN`
 ` - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:56.100 JupyterHub app:1726] Not using allowed_users. Any authenticated user will be allowed.`
`- Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:56.146 JupyterHub app:2419] Initialized 0 spawners in 0.004 seconds`
`  - Jan 18 14:33:56 pipenv[9943]: [W 2021-01-18 14:33:56.151 JupyterHub proxy:529] Found proxy pid file: /opt/jupyterlab/jupyterhub-proxy.pid`
`  - Jan 18 14:33:56 pipenv[9943]: [W 2021-01-18 14:33:56.151 JupyterHub proxy:541] Proxy no longer running at pid=9837`
`  - Jan 18 14:33:56 pipenv[9943]: [W 2021-01-18 14:33:56.153 JupyterHub proxy:663] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...`
`  - Jan 18 14:33:56 pipenv[9943]: [I 2021-01-18 14:33:56.153 JupyterHub proxy:666] Starting proxy @ http://:8080`
`  - Jan 18 14:33:56 pipenv[9943]: 14:33:56.683 [ConfigProxy] info: Proxying http://*:8080 to (no default)`
`  - Jan 18 14:33:56 pipenv[9943]: 14:33:56.695 [ConfigProxy] info: Proxy API at http://127.0.0.1:8082/api/routes`
`  - Jan 18 14:39:42 pipenv[9943]: [C 2021-01-18 14:39:42.610 JupyterHub app:2625] Failed to start proxy`
`  - Jan 18 14:39:42 pipenv[9943]:     Traceback (most recent call last):`
`  - Jan 18 14:39:42 pipenv[9943]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/app.py", line 2623, in start`
`  - Jan 18 14:39:42 pipenv[9943]:         await self.proxy.start()`
`  - Jan 18 14:39:42 pipenv[9943]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/proxy.py", line 700, in start`
 ` - Jan 18 14:39:42 pipenv[9943]:         await server.wait_up(1)`
 ` - Jan 18 14:39:42 pipenv[9943]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/utils.py", line 195, in wait_for_server`
  `- Jan 18 14:39:42 pipenv[9943]:         timeout=timeout,`
  `- Jan 18 14:39:42 pipenv[9943]:       File "/opt/jupyterlab/.venv/lib/python3.7/site-packages/jupyterhub/utils.py", line 183, in exponential_backoff`
  `- Jan 18 14:39:42 pipenv[9943]:         raise TimeoutError(fail_message)`
  `- Jan 18 14:39:42 pipenv[9943]:     TimeoutError: Server at TLD.fr:8080 didn't respond in 1 seconds`
  `- Jan 18 14:39:42 pipenv[9943]:`
  `- Jan 18 14:39:42 systemd[1]: jupyterlab.service: Main process exited, code=exited, status=1/FAILURE`
  `- Jan 18 14:39:42 pipenv[9943]: 14:39:42.866 [ConfigProxy] warn: Terminated`
  `- Jan 18 14:39:42 systemd[1]: jupyterlab.service: Failed with result 'exit-code'.`
  `- Jan 18 14:39:52 systemd[1]: jupyterlab.service: Service RestartSec=10s expired, scheduling restart.`
  `- Jan 18 14:39:52 systemd[1]: jupyterlab.service: Scheduled restart job, restart counter is at 24.`
  `- Jan 18 14:39:52 systemd[1]: Stopped JupyterLab.`
  `- Jan 18 14:39:52 systemd[1]: Started JupyterLab.`
